spring.application.name=server

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}

spring.datasource.hikari.connectionTime=30000
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.maximumPoolSize=8

# Enable multipart form
spring.servlet.multipart.enabled=true 
spring.servlet.multipart.max-file-size=30MB 
spring.servlet.multipart.max-request-size=30MB 
spring.servlet.multipart.file-size-threshold=1MB

do.storage.key=${DO_STORAGE_KEY}
do.storage.secret=${DO_STORAGE_SECRET}
do.storage.endpoint=${DO_STORAGE_ENDPOINT}
do.storage.endpoint.region=${DO_STORAGE_REGION}
do.storage.bucket=${DO_STORAGE_BUCKET}